# Generated by Django 3.2.6 on 2021-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='media/branches')),
                ('pastors_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='media/devotion')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=800)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='media/home')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=800)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
