# Generated by Django 3.2.6 on 2021-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acci_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='content',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.TextField(max_length=800),
        ),
    ]
