# Generated by Django 3.2.6 on 2021-11-18 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acci_main', '0002_auto_20211117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='home',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
